# Use the official Golang base image
FROM golang:1.20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Go modules files and download dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the gRPC server executable
RUN go build -o zkp_auth .

# Expose the port used by the gRPC server
EXPOSE 50051

# Run the gRPC server when the container starts
CMD ["./zkp_auth"]
